"""empty message

Revision ID: 7f53babe9bf0
Revises: 616c0c4e1358
Create Date: 2024-03-20 14:35:00.730633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f53babe9bf0'
down_revision = '616c0c4e1358'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('salt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salt', sa.VARCHAR(length=32), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
